logging:
  freq: 50
  path: LogFiles
  project: null
  eid: null
  wandb:
    activate: True
    team: "dde"

training:
  seed: 1994
  gpus: [0, 1]
  epochs: 40
  batch_size: 32

ckpt:
  resume_from: null
  seed_from: null
  load_fc: True
  imagenet: True

optimizer:
  # do not decay batch norm and bias and FC
  decay_not_bias_norm: 0
  # initial learning rate
  lr: 1e-3
  # eps for adaptive optimizers
  eps: 1e-8
  # Name of LR scheduler
  lr_scheduler_name: 'onecycle'
  # Name of optimizer
  name: 'adamw'
  # Optimizer weight decay
  weight_decay: 1e-2

model:
  backbone: efficientnet_b2
  version: test
  # name of surgery function
  surgery: null

# Dataset should comply with a following directory hierarchy 
# $data_path/
#     $desc.class1/
#         $train_id/
#         $val_id/
#         $test_id/
#     ...
#     $desc.classN/
#         $train_id/
#         $val_id/
#         $test_id/
dataset:
  size: 50
  file_ext: '.jpg'
  decoder: 'NR'
  data_path: '/media/multi_quality_factor/JPEG_standard/'
  pair_constraint: False
  num_workers: 6
  train_id: "TRN"
  test_id: "TST"
  val_id: "VAL"
  # Do not use wilcard now
  desc:
    class1:
      path: "QF75/COVER"
      label: 0
    class2:
      path: "QF75/JUNI_0.4_bpnzac"
      label: 1
    class3:
      path: "QF75/UED_0.3_bpnzac"
      label: 2