logging:
  freq: 50
  path: LogFiles
  project: 'test'
  eid: 'test_run_csv_v2'
  wandb:
    activate: True
    team: "dde"
  monitor:
    metric: 'val/wAUC'
    mode: 'max'

training:
  seed: 1994
  gpus: [0]
  epochs: 100
  batch_size: 64
  precision: '16-mixed'

ckpt:
  resume_from: null
  seed_from: 'https://github.com/DDELab/deepsteganalysis/releases/download/v0.1/jin_srnet.ckpt'
  load_fc: True
  pretrained: True

optimizer:
  # do not decay batch norm and bias and FC
  decay_not_bias_norm: 0
  # initial learning rate
  lr: 1e-3
  # eps for adaptive optimizers
  eps: 1e-4
  # Name of LR scheduler
  lr_scheduler_name: 'onecycle'
  # Name of optimizer
  name: 'adamw'
  # Optimizer weight decay
  weight_decay: 1e-2

model:
  backbone: srnet
  version: test
  # name of surgery function
  surgery: null

## csv should contain label, subset identifier
dataset:
  size: 50
  augs_type: 'spatial_d4'
  decoder: 'gray_spatial'
  data_path: '/mnt/hdd/bossbows2/spatial/'
  num_workers: 6
  train_id: "TRN"
  test_id: "TST"
  val_id: "VAL"
  classes: 2
  desc: '/mnt/hdd/bossbows2/spatial/database.csv'