name: training tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OMP_NUM_THREADS: 2
  MKL_NUM_THREADS: 2

jobs:
  test:
    name: Run tests on ${{ matrix.os }} with Python ${{ matrix.python }}
    strategy:
        os: [ubuntu-24.04]
        python: ['3.12']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install testing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-timeout
    - name: Install torch on ubuntu
      run: |
        sudo apt update
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install git+https://github.com/dwgoon/jpegio
    - name: SRNet training test without PC
      run: |
        python train_lit_model.py config=tests/test_config.yaml
    - name: SRNet training test with PC
      run: |
        python train_lit_model.py config=tests/test_config.yaml dataset.pair_constraint=True training.batch_size=4